### ISSUE TITLE
Cron & Client Area errors: Post-install, errors with API Class (includes) & Client Area info (if no-PVE)

### ISSUE THREAD

**Issue by lsthompson** [The-Network-Crew/Proxmox-VE-for-WHMCS#13]
End user reported error with WHMCS System Cron post-install.

Unable to include the PHP Class for PVE2 API. Pushed tweak to use ROOTDIR prefix.

`ERROR: Error: Failed opening required 'modules/addons/pvewhmcs/proxmox.php' (include_path='.:/usr/share/pear:/usr/share/php') in /sites//billing/modules/servers/pvewhmcs/pvewhmcs.php:5`

Stack trace: 
#0 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): unknown() 
#1 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Product/Server.php(0): WHMCS\Module\AbstractModule->load('pvewhmcs') 
#2 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Product/Server.php(0): WHMCS\Product\Server->getModuleInterface() 
#3 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Cron/Task/TenantUsageMetrics.php(0): WHMCS\Product\Server->getMetricProvider() 
#4 [internal function]: WHMCS\Cron\Task\TenantUsageMetrics->__invoke() 
#5 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): call_user_func_array(Object(WHMCS\Cron\Task\TenantUsageMetrics), Array) 
#6 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() 
#7 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() 
#8 /sites//billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection)) 
#9 /sites//billing/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#10 /sites//billing/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#11 /sites//billing/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#12 /sites//billing/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#13 /sites//billing/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\CliInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#14 {main} {"exception":"[object] (Error(code: 0): Failed opening required 'modules/addons/pvewhmcs/proxmox.php' (include_path='.:/usr/share/pear:/usr/share/php') at /sites//billing/modules/servers/pvewhmcs/pvewhmcs.php:5)"} []

`Error: Failed opening required 'modules/addons/pvewhmcs/proxmox.php' (include_path='.:/usr/share/pear:/usr/share/php') in /sites//billing/modules/servers/pvewhmcs/pvewhmcs.php:5`

LH202321616

**Comment by lsthompson** [comment]
Routed end user to this issue. Pushed commit to prefix ROOTDIR onto API class file: https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/commit/4950738e31c85dc09e6ee59524c3e551d7aac2c2

Need to know update, and whether the module is otherwise functional?

**Comment by elitbiz** [comment]
When I install this module, I can't go to the "additional modules" and an error immediately appears. 

https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/archive/refs/heads/master.zip

**Comment by lsthompson** [comment]
@elitbiz that error would make sense if it can't populate the data / connect, though 

L501: `$vm_status['diskusepercent'] = intval( $vm_status['disk'] * 100 / $vm_status['maxdisk'] );`

Re: Your original Cron error, is that still problematic with each Daily Cron firing?

Re: Proxmox API access, can you verify ANY connections from WHMCS?

**Comment by lsthompson** [comment]
Hi @elitbiz just checking in for an update? Would be great to get it running smoothly for you. :-)

**Comment by WaldperlachFabi** [comment]
Same problem, how can I check if the connection is working currently? When setting up the Server in WHMCS(8.6.0) it connected successfully!

**Comment by lsthompson** [comment]
You should be able to see the connections from your WHMCS server on the Proxmox host in the ```
/var/log/pveproxy/pveproxy.log
``` file.

**Comment by WaldperlachFabi** [comment]
Yes it connects:
::ffff:IP - - [12/06/2023:09:18:23 +0200] "POST /api2/json/access/ticket HTTP/1.1" 200 1325
::ffff:IP - root@pam [12/06/2023:09:18:23 +0200] "GET /api2/json/nodes HTTP/1.1" 200 331
::ffff:IP - root@pam [12/06/2023:09:18:23 +0200] "POST /api2/json/nodes/pve01/lxc HTTP/1.1" 400 164
::ffff:IP - - [12/06/2023:09:18:25 +0200] "POST /api2/json/access/ticket HTTP/1.1" 200 1325
::ffff:IP - root@pam [12/06/2023:09:18:26 +0200] "GET /api2/json/nodes HTTP/1.1" 200 331
::ffff:IP - root@pam [12/06/2023:09:18:26 +0200] "POST /api2/json/nodes/pve01/lxc HTTP/1.1" 400 164
::ffff:IP - - [12/06/2023:09:18:30 +0200] "POST /api2/json/access/ticket HTTP/1.1" 200 1325
::ffff:IP- root@pam [12/06/2023:09:18:30 +0200] "GET /api2/json/nodes HTTP/1.1" 200 331
::ffff:IP - root@pam [12/06/2023:09:18:30 +0200] "POST /api2/json/nodes/pve01/lxc HTTP/1.1" 400 164

**Comment by lsthompson** [comment]
Great. Does it create the VM/CT okay? @elitbiz says that it doesn't for them.

**Comment by WaldperlachFabi** [comment]
No it doesn’t create it, it only throws the error i sent…

**Comment by lsthompson** [comment]
Got it, thanks. This is in Admin Area or Client Area? Screenshot also please.

**Comment by WaldperlachFabi** [comment]
After ordering(with auto setup on) and clicking on the server this shows up in client area:
![IMG_0910](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/67c2b387-a078-4cde-b5cd-d4f70634df27)
![IMG_0911](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/963a7ecb-d33a-4ee7-93e8-d306811734af)
In admin area: 
![IMG_0912](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/51ca9cae-b16f-4371-8234-ea9a1e2375e0)
![IMG_0913](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/24308b1c-ca3a-4714-8606-46ed055aee9a)

**Comment by elitbiz** [comment]
The server does not create an error. whmcs  8.7.2

Same problem.

<img width="909" alt="232323" src="https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/136104317/b65f516b-1c87-4928-812d-f623dea92f23">

**Comment by lsthompson** [comment]
Thank you both! Will work on this and get a test fix to you shortly.

**Comment by lsthompson** [comment]
Hi, please update from master and check Admin + Client areas again?

**Comment by WaldperlachFabi** [comment]
Okay now I get a „VM/CT not found in Cluster Resources.“ page. I get the following error when I want to create it manually in admin panel:
![IMG_8968](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/fab4e089-cdb2-4491-b867-40e244ffc3a5)

if I want to add an IP to an IP pool, the button doesn’t render and I get the following error when trying to add an IP to an pool:
![IMG_8969](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/8cc2e66d-f900-4f49-a2cc-2d0ff8d64ce1)
![IMG_8970](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/3507739e-5263-46b4-b237-cf7063545278)


One more question: for example I have 3 ips assigned to the proxmox Server. 123.456.789.1(main ip of the proxmox server), 123.456.789.4 and 123.456.789.6 how would the ip pool have to look like?

**Comment by WaldperlachFabi** [comment]
Here are the logs of the Proxmox Servher when trying to manually create the server in admin area(with getting the error) and after trying to access it from client area!


::ffff:IP - - [12/06/2023:14:30:44 +0200] "POST /api2/json/access/ticket HTTP/1.1" 200 1325
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes HTTP/1.1" 200 329
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/config HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/cluster/resources HTTP/1.1" 200 736
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13
::ffff:IP - root@pam [12/06/2023:14:30:44 +0200] "GET /api2/json/nodes/pve01//88/rrd HTTP/1.1" 501 13

**Comment by lsthompson** [comment]
Thank you kindly, that's very helpful. I've pushed 2 commits now to master - 1x for IPv4 add, 1x for icon.

As for acceptance of order (ie. provisioning of VM/CT), can you please send any WHMCS/PHP logs that you can see?

If none are being generated or stored, you can change your WHMCS Config to log/display errors. Or use debug mode.

https://docs.whmcs.com/Enabling_Error_Reporting
https://docs.whmcs.com/Troubleshooting_Module_Problems

**Comment by elitbiz** [comment]
WHMCS error display. 
<img width="909" alt="245090097-b65f516b-1c87-4928-812d-f623dea92f23" src="https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/136104317/d17d24a5-3f25-45a2-b788-0e32a76ee552">

**Comment by lsthompson** [comment]
@elitbiz update from master again. That error should be cleared already. 

@WaldperlachFabi thank you, I'll see what we can improve to get the actual error thrown/logged instead.

**Comment by lsthompson** [comment]
What logs do you see on the Proxmox host when you try to accept order?

If you see a clone action, can you try to get more detailed logs for the event?

**Comment by lsthompson** [comment]
Closed #13, moved current troubleshooting to new issue #17
