### ISSUE TITLE
Client Area: Error when opening product(PVE connection ok)

### ISSUE THREAD

**Issue by WaldperlachFabi** [The-Network-Crew/Proxmox-VE-for-WHMCS#19]
No it isn’t working 😂
![IMG_0973](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/490fe8b8-11fb-4221-8dc1-3b952f323f1c)
![IMG_0974](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/80318133/8bad1d2a-f971-4d3e-a8c1-1264f4972109)

Error in module log: ?timeframe=year&ds=cpu&cf=AVERAGE

**Comment by lsthompson** [comment]
At least the comments are gone! haha

Line 592 isn't the first one, so I've unset it now after each call. Does that work?

**Comment by lsthompson** [comment]
Close-ish to bed here @WaldperlachFabi - are you still around for now?

**Comment by lsthompson** [comment]
Can we close this @WaldperlachFabi ?

**Comment by WaldperlachFabi** [comment]
Nope, I were busy yesterday, I am going to test it now:)
