### ISSUE TITLE
(WHMCS > Config > Servers) Connection Test: Blank response = failed test 

### ISSUE THREAD

**Issue by lsthompson** [The-Network-Crew/Proxmox-VE-for-WHMCS#29]
When adding a Server to WHMCS, per #28, the Connection Test fails with no error message. 

A follow-up there seems to show the NEW method is not working, OLD method tests fine.

**Comment by czf00852** [comment]
Is there a tutorial for the old method? Saving without testing, and then retesting won't work either.

**Comment by lsthompson** [comment]
I believe it's to do with the Simple vs Advanced methods for linking a Server to WHMCS. They simplified it and that route doesn't work at the moment - but the longer way should be OK.

**Comment by JrZavaschi** [comment]
Hi,

Try run in your node:
pvesh get /cluster/resources

After this, retry connection test, it work for me.

**Comment by noysteque** [comment]
Hello, i have the same issue, is this being patched for 1.3 ?

**Comment by lsthompson** [comment]
Yes, this should be done in v1.2.3

1 or 2 months away I'd think 😊

**Comment by lsthompson** [comment]
@jbrouhard98 @czf00852 @JrZavaschi

Could you please re-test the Connection Test?

Need to update from repo, not release, to get the fix.

**Comment by lsthompson** [comment]
This is now fixed in the repo, and will be released formally into v1.2.3

Appreciate your patience!
