### ISSUE TITLE
VLAN ID for VMs/CTs: Ability to set the VLAN config per-plan/package

### ISSUE THREAD

**Issue by czf00852** [The-Network-Crew/Proxmox-VE-for-WHMCS#35]
Your module is very good and easy to use. It would be great if you can increase the vlan option of the network card

**Comment by lsthompson** [comment]
Thanks for raising this. https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu defines `net[n]` syntax as:

`[model=]<enum> [,bridge=<bridge>] [,firewall=<1|0>] [,link_down=<1|0>] [,macaddr=<XX:XX:XX:XX:XX:XX>] [,mtu=<integer>] [,queues=<integer>] [,rate=<number>] [,tag=<integer>] [,trunks=<vlanid[;vlanid...]>] [,<model>=<macaddr>]`

So in theory we'd option `[,trunks=<vlanid[;vlanid...]>]` in during creation. It would likely need to be set per-plan.

Or are you suggesting that it should be possible instead to specify the VLAN ID per-service specifically after creation?

**Comment by lsthompson** [comment]
**Ready in v1.2.2 (TBA)** - please update from repo (not releases) and see if that works for you (note the SQL tweak to do)

Please advise if you find any problems with the new function ASAP, or we will close this. Thanks for the suggestion!
