### ISSUE TITLE
VM Creation issue.

### ISSUE THREAD

**Issue by pafeliepixel** [The-Network-Crew/Proxmox-VE-for-WHMCS#37]
Hello,

It seems that I have some issues regarding the creation of the VM after I have placed an order for myself, to test it out.

It gives out this error, it is not a PHP error, just a legitimate return error after I did not do something right.

"PVE2 API: This API Request Failed. HTTP CODE: 400, HTTP ERROR: HTTP/1.1 400 Parameter verification failed., REPLY INFO: {"errors":{"vmid":"invalid format - value does not look like a valid VM ID\n"},"data":null}"

I'm looking at my config and I don't seem to find what is wrong and what represents the "vmid" field in the creation process, or rather in the process of parsing the info.

Could you guys help me a bit? I'll gladly supply further info and logs if needed.

The environment consists of:
Proxmox VE 8.0.3
cPanel 114.0.5
Whmcs 8.6.1
Php 8.1

Thank you.

**Comment by lsthompson** [comment]
Please read the README.

Do you have >100 WHMCS Services?

**Comment by pafeliepixel** [comment]
Hey,

I have read that "README" section, most of slipped my mind. I don't have 100+ services on my whmcs installation. 

Should be fine spawning those on a single account?

**Comment by lsthompson** [comment]
Yes, just need more than 100 in WHMCS. Else it's invalid in Proxmox as they reserve VMIDs below 100.

**Comment by pafeliepixel** [comment]
> Yes, just need more than 100 in WHMCS. Else it's invalid in Proxmox as they reserve VMIDs below 100.

Thank you for your help.

Have a great day ahead :D
