### ISSUE TITLE
Include a way for the client to mount a ISO/CDROM from Repository 

### ISSUE THREAD

**Issue by jbrouhard98** [The-Network-Crew/Proxmox-VE-for-WHMCS#41]
**Is your feature request related to a problem? Please describe.**
no problem exists for this.

**Describe the solution you'd like**
After creation of VM, a CDROM option should be available.   Allow the client to mount an ISO to install their OS of choice  (assuming that the VM is created without a cloud init clone) 

**Describe alternatives you've considered**
Can do it manually from PVE itself.   However it doesn't really give a client the option to do this from WHMCS.

**Additional context**
This might be more niche use case, but I do get some clients that prefer to install the OS themselves, vs using a pre-built image.   There's a lot of reasons for this, but a good majority of my clients either request this, or have me do the installation myself.   Thought it might be a good feature request in the event a client does request this kind of set up.

**Comment by lsthompson** [comment]
This exists already if it's chosen during order. There is an ISO method.

You need to have the vztmpl ISO contents on the host/s though.

**Comment by jbrouhard98** [comment]
Huh.. i must have missed that.   It's looking in local/ISOs isn't it ?

**Comment by jbrouhard98** [comment]
Just tried to order, so I'm guessing it's looking for ISO's locally to the PVE node by default.    Can this be an option added to the Product Details  at some point as well??

**Comment by lsthompson** [comment]
The /manual/ PDF files cover it.

README needs more work. :-)

Yeah but you fully declare the path so it could be on-host where it suits you.

**Comment by lsthompson** [comment]
Is this all good to close? Documentation needs improving but ISO is working.

**Comment by jbrouhard98** [comment]
AH!   my bad.    yes, go ahead and close
