### ISSUE TITLE
Ability to set VMID starting range.

### ISSUE THREAD

**Issue by johncsuti** [The-Network-Crew/Proxmox-VE-for-WHMCS#42]
**Is your feature request related to a problem? Please describe.**
It would be very helpful if you could specify a starting VM and LXC ID instead of setting over 100 dummy VM's onto a dummy user.

**Describe the solution you'd like**
Ability to set a starting VMID at something like 1000 so you can easily tell the difference between Manually configured VM's and WHMCS configured VM's.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by lsthompson** [comment]
We don't plan to do this, as the WHMCS Service ID is used for VM ID intentionally. You can spool up fake services until you are over 1,000 - that will solve your problem.

ie. Add Order to fake client profile, add useless things until you have WHMCS + Order = over 1k total, and you're done.
