### ISSUE TITLE
An error occurs when accepting an order

### ISSUE THREAD

**Issue by Max1631** [The-Network-Crew/Proxmox-VE-for-WHMCS#51]
**Describe the bug**
I have an order, I want to accept it and a container should be created. 
But I get the following error and can not make sense of it:

PVE2 API: This API Request Failed. HTTP CODE: 500, HTTP ERROR: HTTP/1.1 500 unable to parse directory volume name 'vztmpl/', REPLY INFO: {"data":null}

**Screenshots**
If applicable, add screenshots to help explain your problem to us.

Proxmox VE for WHMCS v1.2.2 (GitHub reports latest as v1.2.2)
PHP v8.1.22 running on Apache Web Server
- Version of module: Currently
- PHP version 8.1

**WHMCS Information (please complete the following):**
 - WHMCS Version Currently
 - Using HTTPS: Yes

**Confirm that you have MORE THAN 100 services (all statuses) in WHMCS?**
Yes.

**Comment by lsthompson** [comment]
The part of the error you need to focus on is `unable to parse directory volume name 'vztmpl/'` which sounds like ISO/TPL territory to me. 

Can you send screenshots of your ISO config please? I'd say it's not quite right. The manual PDFs are outdated though should be somewhat helpful.

**Comment by Max1631** [comment]
Good morning, the ISO template from Proxmox or where? What exactly do you want to see there?

**Comment by lsthompson** [comment]
Where you have the ISO stored on your Proxmox host. Like a full CLI Screenshot or copy paste.

What you have set in WHMCS config for the ISO file location. It has to be right or it will throw errors.

Module Plan configuration for VM type. 

WHMCS Service (system, not client) config, all tabs and info. 

Those 4 things to start with please.
