### ISSUE TITLE
(WHMCS Admin > Servers > PVE Host) root > root@pve

### ISSUE THREAD

**Issue by VermiumSifell** [The-Network-Crew/Proxmox-VE-for-WHMCS#52]
Can I get some help? What information is needed and how do I retrieve it to get help?

**Comment by lsthompson** [comment]
You've given zero info.

Explain the issue. Provide context. List what you have tried. Confirm you have read the entire README. Explain what testing you've done up to this point.

etc etc

**Comment by lsthompson** [comment]
What configuration is saved in WHMCS Admin > Servers > your hypervisor?

The connection test is buggy, but if you give the right details it will connect OK.

**Comment by lsthompson** [comment]
root >> root@pve or root@pam

When you login to PVE in a browser, it will have a realm selected. You cannot forego that in the module config.

**Comment by lsthompson** [comment]
I've updated the README.md to better explain PVE's authentication realm requirement.

If you have any problems once you've updated your credentials, please raise a proper issue.

**Comment by lsthompson** [comment]
Certificate should not matter. That's not the PVE setup.

Please show all of your config, and prove that your web server can reach your hypervisor via other methods.

**Comment by jbrouhard98** [comment]
Your issues are not related to SID/VMID issues.   And no there is no real better implementation as it matches a service ID (SID) to a Virtual Machine.

your issue is that somehow, you are either a) not authenticating or b) using the wrong username/password combination.  Another thing to note is you have your "hostname" set to your domain name.

**Comment by lsthompson** [comment]
SID = VMID is sane as mentioned already here, thanks @jbrouhard98

Are you sure it is root@pam and that your Domain Name routes to the proper IP? Many people use this module successfully. 

I asked a question you ignored. Prove that your WHMCS Web Server can connect to your PVE Server via the normal port. ie. Show it is conceptually doable via the networks in-place.

**Comment by lsthompson** [comment]
The code looks to use the IP, and to add "pam" automatically so root is ok.

So it's more likely that you have a Routing issue. Please send the connection proof as before.

**Comment by jbrouhard98** [comment]
That's not what he asked.   He asked to prove that your whmcs is actually connecting to that service.  Not that YOU can via curl
