### ISSUE TITLE
WHMCS Connection Test (#29 dup); /nodes/pve//#/config (2x / = illegal op) return of #36?

### ISSUE THREAD

**Issue by wawelon** [The-Network-Crew/Proxmox-VE-for-WHMCS#53]
Error - test connect

PVE2 API: This API Request Failed. 
HTTP CODE: 401, 
HTTP ERROR: HTTP/1.1 401 No ticket, 
REPLY INFO:

**Comment by wawelon** [comment]
client area services 
PVE2_Exception: PVE2 API: This API Request Failed.
HTTP CODE: 401,
HTTP ERROR: HTTP/1.1 401 No ticket,
REPLY INFO: in /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php:264
Stack trace:
#0 /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php(574): PVE2_API->action('/nodes', 'GET')
#1 /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php(291): PVE2_API->get('/nodes')
#2 /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php(120): PVE2_API->reload_node_list()
#3 /sites/noeye.pp.ua/modules/servers/pvewhmcs/pvewhmcs.php(608): PVE2_API->login()
#4 [internal function]: pvewhmcs_ClientArea(Array)
#5 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('pvewhmcs_Client...', Array)
#6 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('ClientArea', Array)
#7 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Service.php(0): WHMCS\Module\Server->call('ClientArea', Array)
#8 /sites/noeye.pp.ua/clientarea.php(0): WHMCS\Service->moduleCall('ClientArea', Array)
#9 {main}

**Comment by lsthompson** [comment]
So yes, it was, and now you've tested via another way? Same error if so, no PVE auth ticket. 

What do your Proxmox logs say when you attempt these actions? 

You're sure you've done all the module config steps?

**Comment by wawelon** [comment]
> Так что да, так и было, а теперь вы проверили другим способом? Если да, то та же ошибка: нет билета аутентификации PVE.
> 
> Что говорят ваши журналы Proxmox, когда вы пытаетесь выполнить эти действия? Success
> 
> Вы уверены, что выполнили все шаги по настройке модуля? YES

New Error

PVE2_Exception: PVE2 API: This API Request Failed.
HTTP CODE: 501,
HTTP ERROR: HTTP/1.1 501 Method 'GET /nodes/pve//2/config' not implemented,
REPLY INFO: {"data":null} in /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php:264
Stack trace:
#0 /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php(574): PVE2_API->action('/nodes/pve//2/c...', 'GET')
#1 /sites/noeye.pp.ua/modules/servers/pvewhmcs/pvewhmcs.php(616): PVE2_API->get('/nodes/pve//2/c...')
#2 [internal function]: pvewhmcs_ClientArea(Array)
#3 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('pvewhmcs_Client...', Array)
#4 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('ClientArea', Array)
#5 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Service.php(0): WHMCS\Module\Server->call('ClientArea', Array)
#6 /sites/noeye.pp.ua/clientarea.php(0): WHMCS\Service->moduleCall('ClientArea', Array)
#7 {main}

help please

**Comment by lsthompson** [comment]
>  HTTP ERROR: HTTP/1.1 501 Method 'GET /nodes/pve//2/config' not implemented,

This sounds like a misconfiguration in your setup. Others would be reporting it if not.

Are you able to share screenshots of all of your configuration areas please, for us to check?

The format is wrong. The code mentioned pulls it together as:
`$vm_config=$proxmox->get('/nodes/'.$first_node.'/'.$guest->vtype.'/'.$params['serviceid'] .'/config') ;`

So we should be seeing more like `/nodes/1/qemu/101/config` in the request, if all is configured OK.

Did you explicitly save the WHMCS Service with the Module Plan against it, via WHMCS Settings? I would think so, as per #36 there should be an error that tells you about that condition, and to fix it.

**Comment by wawelon** [comment]
![Без імені](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/f07009fe-3393-46b0-94ef-ab1b9dd2dd35)
![Без імені2](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/6caae47a-ecea-4dbf-8330-ce75caa8d532)
![Без імені3](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/e5747921-01a9-4fdf-aad2-5b57285bc701)

I didn't use whmcs
Now I’m testing what and how to create my own vps service

**Comment by lsthompson** [comment]
> I didn't use whmcs

What do you mean? How were you doing it?

>  Now I’m testing what and how to create my own vps service

What about your WHMCS > Settings > Products/Services > Service for PVE VM/CT tabs/config?

**Comment by wawelon** [comment]
![Без імені4](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/16249c51-b9c4-45c4-8a5a-8cca5f3ce48a)
this config?

**Comment by lsthompson** [comment]
Hit save there, and then send screenshot of the next tab along too - Custom Fields.

**Comment by wawelon** [comment]
![Без імені6](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/09310f97-e7b6-4250-b7dc-016c3a99db11)

**Comment by lsthompson** [comment]
OK, so you haven't fully followed README.md instructions? Need to have a way to provision it.

https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS#%EF%B8%8F-vmct-plans-setting-everything-up-%EF%B8%8F

As I've asked before, can you please make sure you've followed the full configuration properly? Thanks!

**Comment by wawelon** [comment]
I don’t understand anything how to configure it correctly

**Comment by lsthompson** [comment]
Okay, thanks for letting us know.

Unfortunately you will need to spend more time getting to understand the configuration so you can get it working properly in your environment.

Once you're across the requirements and have it prepared properly please raise a new issue with comprehensive information. Thanks!
