### ISSUE TITLE
HELP i can't figure out the problem /nodes/pve2//12/config' not implemented,

### ISSUE THREAD

**Issue by wawelon** [The-Network-Crew/Proxmox-VE-for-WHMCS#54]
PVE2_Exception: PVE2 API: This API Request Failed.
HTTP CODE: 501,
HTTP ERROR: HTTP/1.1 501 Method 'GET /nodes/pve2//12/config' not implemented,
REPLY INFO: {"data":null} in /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php:264
Stack trace:
#0 /sites/noeye.pp.ua/modules/addons/pvewhmcs/proxmox.php(574): PVE2_API->action('/nodes/pve2//12...', 'GET')
#1 /sites/noeye.pp.ua/modules/servers/pvewhmcs/pvewhmcs.php(616): PVE2_API->get('/nodes/pve2//12...')
#2 [internal function]: pvewhmcs_ClientArea(Array)
#3 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('pvewhmcs_Client...', Array)
#4 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('ClientArea', Array)
#5 /sites/noeye.pp.ua/vendor/whmcs/whmcs-foundation/lib/Service.php(0): WHMCS\Module\Server->call('ClientArea', Array)
#6 /sites/noeye.pp.ua/clientarea.php(0): WHMCS\Service->moduleCall('ClientArea', Array)
#7 {main}

![g1](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/dfdf212a-6f6c-49b4-9cdb-0e9bcc29c7f5)
![g2](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/5d4d6c11-9477-4753-83ec-ece9116d6e3f)
![g3](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/184f1d49-b485-463c-b700-ca4e0d32c6e4)
![g4](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/d73ae6de-b97f-4d83-b27f-a298f7566b2f)
![g5](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/2638a373-cf8e-4274-a1e1-81bf701642c8)

**Comment by wawelon** [comment]
WHMCS Admin > Config > Servers > Add your PVE host/s (user: root; IP: PVE's)  DONE!
WHMCS Admin > Addons > Proxmox VE for WHMCS > Module Config > VNC Secret (see below) DONE!
WHMCS Admin > Addons > Proxmox VE for WHMCS > Add KVM/LXC Plan/s DONE!
WHMCS Admin > Addons > Proxmox VE for WHMCS > Add an IP Pool DONE!
WHMCS Admin > Config > Products/Services > New Service (create offering) DONE!
" " > Newly-added Service > Tab 3 > SAVE (links Module Plan to WHMCS Service type) DONE!

Create User Group "VNC" via PVE > Datacenter / Permissions / Group DONE!
Create new User "vnc" > Datacenter / Permissions / Users - select Group: "VNC", Realm: pve DONE!
Create new Role -> Datacenter / Permissions / Roles - select Name: "VNC", Privileges: VM.Console (only) DONE!
Add permission to access VNC -> Datacenter / Node / VM / Permissions / Add Group Permissions - select Group: "VNC", Role: "VNC" DONE!
Configure the WHMCS > Modules > Proxmox VE for WHMCS > Module Config > VNC Secret with 'vnc' password. DONE!

Why does not it work? Please help me Thank's

**Comment by lsthompson** [comment]
Thanks for showing that you've now read part of the instructions.

You've missed the entire section about the creation method. Seems you're using a template for that?

The error is not the error you've supplied. It has changed. It now speaks to one that we explain at length in the README. 

Create a nothing order with however many services (not Proxmox, just blank module) are required to get your tblhosting.id column in the WHMCS DB to be over 100.

**Comment by wawelon** [comment]
OK it's ready what this error
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ipaddress' cannot be null (SQL: insert into `mod_pvewhmcs_vms` (`id`, `user_id`, `vtype`, `ipaddress`, `subnetmask`, `gateway`, `created`) values (192, 2, qemu, ?, ?, ?, 2023-11-26 00:34:31))

**Comment by lsthompson** [comment]
Check your IP Pool settings in the module, and then the tab on the WHMCS Service type (in settings) needs to be saved with the Plan and Pool. You're missing some IP config.

**Comment by wawelon** [comment]
![Без імен2і](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/ce632b33-1136-4df4-bcd1-8cc87583902c)
![Без імені](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/48e4a9a9-546c-494b-b2a4-806be6c57fb0)

everything seems to be correct

**Comment by lsthompson** [comment]
Thanks. Show me inside each Pool?

Also, save that second Screenshot page. Even though it looks fine.

**Comment by wawelon** [comment]
![Без іме2ні](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/63623486/522a3f22-a141-4e4f-aec4-1515047cf279)

there is nothing inside the pool, although it is created

**Comment by lsthompson** [comment]
Fairly sure you're going to need a new Pool which is large enough to have assignable space within it.

**Comment by wawelon** [comment]
OK it's ready, last problem novnc connect my private ip and it doesn't connect
https://noeye.pp.ua/modules/servers/pvewhmcs/novnc/vnc.html?autoconnect=true&encrypt=true&host=10.10.10.16&port=8006&password=

**Comment by lsthompson** [comment]
....README.

This is explained.

You can fix it otherwise.
