### ISSUE TITLE
Server Not Connecting, Test Connection Failed & Unable to contact Hypervisor

### ISSUE THREAD

**Issue by shehrozblogger** [The-Network-Crew/Proxmox-VE-for-WHMCS#55]
All details are right I checkd many times but still Test Connection is not connecting to server! When I click on test connection it shows attempting to server and than show red color empty square. 
Issue no 2: 
When Client clicks on service it show error message "Unable to contact Hypervisor - aborting!
Please contact Tech Support."

**Comment by lsthompson** [comment]
If you'd read the README then you'd know the test is not currently OK.

Check your Proxmox logs, make sure you read and follow the README, and come back when you can list out every step you've taken to configure it all.

**Comment by shehrozblogger** [comment]
Issue no 2:
When Client clicks on service it show error message "Unable to contact Hypervisor - aborting!
Please contact Tech Support."

**Comment by lsthompson** [comment]
README file needs reading. Thanks. 

Share every single page of relevant config for any other potential help.
