### ISSUE TITLE
Division by Zero (Client Area): CT/LXC Service, Swap value reports as zero = DBZ Error

### ISSUE THREAD

**Issue by PureSoulGO** [The-Network-Crew/Proxmox-VE-for-WHMCS#63]
DivisionByZeroError: Division by zero in /var/www/vhosts/(((((((((mypath))))))))))/httpdocs/modules/servers/pvewhmcs/pvewhmcs.php:714
Stack trace:
#0 [internal function]: pvewhmcs_ClientArea()
#1 /var/www/vhosts/(((((((((mypath))))))))))/httpdocs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func()
#2 /var/www/vhosts/(((((((((mypath))))))))))/httpdocs/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call()
#3 /var/www/vhosts/(((((((((mypath))))))))))/httpdocs/vendor/whmcs/whmcs-foundation/lib/Service.php(0): WHMCS\Module\Server->call()
#4 /var/www/vhosts/(((((((((mypath))))))))))/httpdocs/clientarea.php(0): WHMCS\Service->moduleCall()
#5 {main}

What is this ?

**This happens when I want to access an active service in the customer area after it has been created

The creation works without any problems, but when I want to manage the product as a customer I get this error**

**Comment by PureSoulGO** [comment]
This happens when I want to access an active service in the customer area after it has been created

The creation works without any problems, but when I want to manage the product as a customer I get this error

**Comment by lsthompson** [comment]
Hmm, so you have an LXC service not QEMU, and the issue comes from it getting no value for CT Swap?

```
if ($guest->vtype == 'lxc') {
	$ct_specific=$proxmox->get('/nodes/'.$first_node.'/lxc/'.$params['serviceid'] .'/status/current') ;
	$vm_status['swapusepercent'] = intval($ct_specific['swap'] * 100 / $ct_specific['maxswap']);
}
```

The 2nd nested line is L714. Haven't had this issue reported in ages, so I'd say it's a local issue to you.

Still, I'll give it a day or two, let's try to work out what's up in your case. Does it have Swap in PVE?
