### ISSUE TITLE
Why does the module use IP instead of domain name to connect to pve?

### ISSUE THREAD

**Issue by MoeclubM** [The-Network-Crew/Proxmox-VE-for-WHMCS#64]
**Is your feature request related to a problem? Please describe.**

I found that the plugin uses the set ip instead of the address (domain name) when communicating with pve, but there is no problem with the variable naming in addons' proxmox.php.

**Describe the solution you'd like**

Use the server address instead of the server's IP for communication, modify the variable naming, or add setting items directly to allow users to customize the communication address.
**Describe alternatives you've considered**

My site has been unable to connect to pve, once a vm is created/removed/user visits the product details site it becomes inaccessible, but I don't get any errors and the site tends to come back to normal after two minutes (I spent a lot of time on this time, which I suspect is caused by connection issues)

In addition, the plug-in in the server folder will read the proxmox.php file across folders. I think it may be better to separate it into two parts (because the server/addons two parts basically operate completely independently)

**Additional context**

**Comment by lsthompson** [comment]
> Use the server address instead of the server's IP for communication, modify the variable naming, or add setting items directly to allow users to customize the communication address.

There's no convincing reason to make this change that you've presented.

> My site has been unable to connect to pve, once a vm is created/removed/user visits the product details site it becomes inaccessible, but I don't get any errors and the site tends to come back to normal after two minutes

You need to enable PHP display_errors, as well as Display Errors in WHMCS, and then check the logs available as well as seeing if it throws anything for you. The interface won't refresh live, as START/etc jobs (ACPI) trigger a worker process to finish the job, hence although we say "completed" it is not fully available as a refreshed status in that moment.

> In addition, the plug-in in the server folder will read the proxmox.php file across folders. I think it may be better to separate it into two parts (because the server/addons two parts basically operate completely independently)

This comes from a lack of understanding about how the module is built. The server facet makes the connections.

The addon facet does the client area work and the in-between stuff that isn't /servers/ appropriate workload.

If you have further issues that relate, I am closing this however please comment with logs/etc in #63
