### ISSUE TITLE
CT Creating issue

### ISSUE THREAD

**Issue by alexkong1123** [The-Network-Crew/Proxmox-VE-for-WHMCS#65]
```PVE2 API: This API Request Failed. HTTP CODE: 500, HTTP ERROR: HTTP/1.1 500 lvm name 'vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz' contains illegal characters, REPLY INFO: {"data":null}```
![image](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/103373823/1ffc1181-cd6c-46c8-9d8d-9fc387be8dc6)
![image](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/103373823/67540fec-bd49-4882-8380-3f9ea71171c5)

**Comment by lsthompson** [comment]
Can you please share all of your configurations, CT Plan, WHMCS Service Configs, etc etc?

**Comment by alexkong1123** [comment]
![image](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/103373823/f94d35e2-50f1-4577-84c8-bead03545527)
![image](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/103373823/e65c9d6d-ddb5-4973-8440-bbbc46872a8c)
![image](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/103373823/8fcfa8e0-a568-44fd-9715-c4c49d3c800f)

**Comment by lsthompson** [comment]
Hmm, the error suggests that it's to do with your template.

> lvm name `'vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'` contains illegal characters

Have you read the entire README? For instance, the label being set?

>  ubuntu-99.99-standard_amd64.tar.gz|Ubuntu 99

**Comment by alexkong1123** [comment]
Still not working.

**Comment by lsthompson** [comment]
That's not a response.

Read the README before responding here again. Thank you.
