### ISSUE TITLE
Email Template - Main IP EMPTY

### ISSUE THREAD

**Issue by ItzT0kyooFR** [The-Network-Crew/Proxmox-VE-for-WHMCS#66]
**Issue Description:**
The Main IP field in email templates is currently displaying as empty.

**Requested Solution:**
I propose the implementation of a custom variable that can be utilized within email templates to dynamically showcase the IP address of the virtual machine.

**Alternatives Considered:**
None at the moment.

**Additional Context:**
For better clarity, I have attached a screenshot illustrating the current state of the Main IP field in the email templates.
![Screenshot_3](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/93414479/7fa70f48-b721-495d-b508-94693ccd91dd)

**Comment by lsthompson** [comment]
Thanks for this. Do you have the IP set in the WHMCS Client Service as well as the Module Service?

**Comment by lsthompson** [comment]
I'm not convinced that any changes are needed. If anything, it would be to duplicate the IP into the WHMCS Service field, from the Module Service field*. However that can also be done manually at-deployment.

* doing this would need updating logic also, as if the IP changed in-module/PVE, then it needs updating in WHMCS too.

Please let me know your thoughts - happy to re-consider if you're able to respond quickly (I commented 1 month ago)
