### ISSUE TITLE
db.sql not found

### ISSUE THREAD

**Issue by wotuthink** [The-Network-Crew/Proxmox-VE-for-WHMCS#67]
Upload the module in WHMCS. But when try to activate the module it says db.sql not found. Whereas, it exists in the pvewhmcs directory. Even after giving full permissions it stays same. Not activating.

**Comment by lsthompson** [comment]
G'day, try to update from the repo (not releases), and see if it activates cleanly now? Thanks!

**Comment by wotuthink** [comment]
Nope. Didn't worked.

**Comment by lsthompson** [comment]
What is your Web server stack and config? It is making a relative call.

**Comment by wotuthink** [comment]
Cpanel with WHMCS installed on domain root directory.

**Comment by lsthompson** [comment]
Strange. Please try from the repo again, see if that helps?

Might need you to add some debugging statements if no good.

**Comment by wotuthink** [comment]
Re-download the report and it worked. Thanks
