### ISSUE TITLE
Failed to create CT (missing credentials?)

### ISSUE THREAD

**Issue by eakteam** [The-Network-Crew/Proxmox-VE-for-WHMCS#70]
When trying to create the order it shows 

`Module Command Error PVE2 API: Hostname/Username/Realm/Password/Port required for PVE2_API object constructor.`

I followed all intructions, but not being able to solve that...

![whmcs](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/8820741/4245e0ee-555b-491f-a746-f9c7b5c30696)

![whmcs2](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/8820741/a6ba5b0d-45d2-4303-ba8f-29ba2e98d527)

Also step 4 `(Add permission to access VNC -> Datacenter / Node / VM / Permissions / Add Group Permissions - select Group: "VNC", Role: "VNC")`  is little confusing since there is no seetings in the node for vm, or we should select random existing vm and after that going to the permissions?

**Comment by lsthompson** [comment]
Strange. It seems you don't have the root password entered into WHMCS > Servers > PVE Host?

That would explain the first problem you're having. Please check and write back.

Re: VNC, you need to add the user at node/DC-level, not VM-level.

**Comment by lsthompson** [comment]
What do you see in the Module Log with Debug Mode enabled within the Module Config?

**Comment by lsthompson** [comment]
@johncsuti @eakteam curious about what you both see with Debug Mode enabled.

Please update from the repo itself before trying again, including SQL Updates.

Also, if you could step out your process that would help us replicate it.

**Comment by lsthompson** [comment]
@johncsuti @eakteam - following up the above.

Would be great to hear back with debugging ON etc.

**Comment by lsthompson** [comment]
Also, the Connection Test should now relay the problem back. 

Properly tidied the logic there just now. Shouldn't false-positive if you update from the repo.

**Comment by lsthompson** [comment]
If you update from the repo itself (SQL tweaks too), without Debug Mode that test _failing_ will now go to Module Debug Log.

Please let us know what you're able to un-earth now that the Connection Tester and Module Debug Log gives you insights!

**Comment by nakedgoat** [comment]
Having pretty much same issue what was the fix?
