### ISSUE TITLE
Node IP Assignment issue

### ISSUE THREAD

**Issue by kromr6487** [The-Network-Crew/Proxmox-VE-for-WHMCS#71]
Config step-by-step guide has been followed to a t (excluding VNC as I am doing that after resolving this issue). For whatever reason when I FIRST configured it (I have 2 nodes on a cluster) I set it for "planetaryhosting" I went to swap it to "panel-planetary-hosting" and it is still attempting to run the WHMCS create module to the "planetaryhosting" node. Is there any insight on how to resolve this?
![Screenshot_20240331_140247_Chrome](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/46402468/29a59335-975d-4499-8595-384c9b337521)

**Comment by lsthompson** [comment]
It refers to the PVE Cluster itself for the first node:

	$nodes = $proxmox->get_node_list();
	$first_node = $nodes[0];
