### ISSUE TITLE
Timeout Error During VNC Connection

### ISSUE THREAD

**Issue by Cornelius3733** [The-Network-Crew/Proxmox-VE-for-WHMCS#72]
**Describe the bug**
When attempting to establish a VNC connection to a Proxmox server through the WHMCS module, we encounter a timeout error. The error message in the Proxmox log is as follows:

May 05 00:22:20 EDVTS002 pvedaemon[2666420]: <vnc@pve> end task UPID:EDVTS002:0028D410:0476FBC7:6636B512:vncproxy:247:vnc@pve: connection timed out

**To Reproduce**
Establish a VNC connection via WHMCS.

**Expected behaviour**
VNC connection should be established.

**Screenshots**
![Screenshot 2024-05-05 003930](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/168939162/cd5a816d-98e3-41fd-ba81-d7e0acccead4)
![Screenshot 2024-05-05 003720](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/168939162/02d6666e-84df-48e5-ab3f-2394d0300453)

**Module > Support/Health tab (remove IP and paste here):**
Proxmox VE for WHMCS v1.2.3 (GitHub reports latest as v1.2.3)
PHP v8.1.28 running on Apache Web Server (xx.com)

**WHMCS Information (please complete the following):**
- v8.10

**Confirm that you have MORE THAN 100 services (all statuses) in WHMCS?**
yes

**Comment by lsthompson** [comment]
Does noVNC work or same issue?

**Comment by Cornelius3733** [comment]
noVNC has the same issue.

**Comment by lsthompson** [comment]
Please go through the README in full, and confirm that you meet the VNC requirements in full?

**Comment by Cornelius3733** [comment]
Hi, thanks for the help, after configuring the WHMCS subdomain and the PTR entry it now works.
