### ISSUE TITLE
Can't activate module

### ISSUE THREAD

**Issue by Ahmad-SDev** [The-Network-Crew/Proxmox-VE-for-WHMCS#78]
When trying to activate the module i get this error,

![image](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/assets/148844305/b6b1bf70-3e9f-4773-bf31-db3d49b9eea6)

**Comment by lsthompson** [comment]
Hi there, please try updating the files from the repository itself - and see how you go.

Given the error, I'm assuming you were UPGRADING and not INSTALLING? Thanks.
