### ISSUE TITLE
Getting the error "An Unknown Error Occurred" and im not sure what is wrong

### ISSUE THREAD

**Issue by leoskinnertm** [The-Network-Crew/Proxmox-VE-for-WHMCS#82]
i followed all the instructions and its still not working and yes i have tried with and without pam and pve and still nothing i have removed the ip and still nothing.
![issue](https://github.com/user-attachments/assets/9eeca323-8bbf-424b-ab20-ffb513322f4d)

**Comment by lsthompson** [comment]
What does the Module Debug Log tell you about it?

**Comment by leoskinnertm** [comment]
where would i find that its my first time using whmcs so don't know where stuff is yet

**Comment by lsthompson** [comment]
Are you sure that your PVE node name can be resolved to an IP Address which WHMCS can access?

Re: logs, the Module Debug Log should contain more information as this failure logs to it:
https://docs.whmcs.com/troubleshooting/logs-in-whmcs/#module-log

**Configuration > System Logs > Module Log**

Read up on the WHMCS documentation and come back with proper information please. Thank you.

**Comment by leoskinnertm** [comment]
ok logs have been enabled and i tried doing it again and there are no logs at all

**Comment by lsthompson** [comment]
So you enabled the System Module Debug Log, then saved PVE Host config in WHMCS > Servers, then tried to Test Connection, and there is nothing visible in the System Module Debug Log once you refreshed the log page?

Your installation of WHMCS is starting to sound problematic, as the PVEWHMCS module [always](https://github.com/The-Network-Crew/Proxmox-VE-for-WHMCS/blob/7dafde094b34c336e49acc6845dafee25cf792f3/modules/servers/pvewhmcs/pvewhmcs.php#L393) logs failures there.

Please raise a ticket with WHMCS Support and ask them to give you the all-clear that nothing would be stopping it.

**Comment by leoskinnertm** [comment]
ok will do thanks for your help

**Comment by AVSISP** [comment]
I can confirm this is 100% not a WHMCS issue and is happening with me too. I am thinking it may be related to SSL. It needs to validate the SSL I think. Testing now to see if with a valid SSL and different domain (subdomain) pointed directly at the IP it will work. I think IP based only does not work if certificate is the pre-generated one.
