### ISSUE TITLE
PVEWHMCS Error: Missing Config

### ISSUE THREAD

**Issue by carcedes** [The-Network-Crew/Proxmox-VE-for-WHMCS#94]
I have added a plan after the pdf with "Creating products by using KVM templates" and I only select the IP Pool tab and have not created a plan bc I want to use the template. Now I can't create a new order:

`Error: PVEWHMCS Error: Missing Config. Service/Product WHMCS Config not saved (Plan/Pool not assigned to WHMCS Service type). Check Support/Health tab in Module Config for info. Quick and easy fix.`

No other logs

Can someone pls help me?

**Comment by lsthompson** [comment]
The template is just the contents. You also need a plan, which you'd then select alongside IP Pool.

That will clear the error and you will be on your way.
